name: app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.0
  flutter_bloc: ^7.0.0
  font_awesome_flutter: ^10.4.0
  email_validator: ^2.1.17
  carousel_slider: ^4.2.1
  url_launcher: ^6.0.12
  image_picker: ^0.8.4
  file_picker: ^4.6.1
  dio: ^4.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
